export const MOVIES_NOW_PLAYING = "MOVIES_NOW_PLAYING";
export const POPULAR_MOVIES = "MOVIES_POPULAR";
export const MOVIES_TOP_RATED = "MOVIES_TOP_RATED";
export const MOVIES_UPCOMING = "MOVIES_UPCOMING";

export const POPULAR_PEOPLE = "POPULAR_PEOPLE";
export const PERSONE = "PERSONE";

export const CHANGE_TV_SHOW = "CHANGE_TV_SHOW";
export const CHANGE_MOVIE = "CHANGE_MOVIE";

export const TRENDING_MOVIES_DAY = "TRENDING_MOVIES_DAY";
export const TRENDING_MOVIES_WEEK = "TRENDING_MOVIES_WEEK";

export const POPULAR_TV_SHOWS = "POPULAR_TV_SHOWS";
export const AIRING_TODAY_TV_SHOWS = "POPULAR_TV_SHOWS";
export const ON_THE_AIR_TV_SHOWS = "POPULAR_TV_SHOWS";
export const TOP_RATED_TV_SHOWS = "POPULAR_TV_SHOWS";
